title:     'FabZero 2023'
email:      info@fabzero.ei
description: "Website voor de FabZero Opleiding"
author: "B. Malengier"

permalink: /:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - changelog.md

include: 
  - _pages
  
# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: "IngegnoMakerSpace"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/
  lesinhouden:
    output: true
    permalink: /lesinhouden/:path/


# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
